---
all:
  children:
    root:
      hosts:
        oda_root:
          ansible_host: 0.0.0.0 # replace with the actual IP address of the root node

    child:
      hosts:
        oda_child_1:
          ansible_host: 0.0.0.0 # replace with the actual IP address of the first child node
        oda_child_2:
          ansible_host: 0.0.0.0 # replace with the actual IP address of the second child node
