---
- name: create oda base deployment directory
  file:
    path: "{{ oda_deploy_path }}"
    state: directory
    mode: '0700'

- name: create secrets subdirectory, open to container
  file:
    path: "{{ oda_deploy_path }}/secrets"
    state: directory
    mode: '0755'

- name: create child-specific secret directories to enforce isolation
  file:
    path: "{{ oda_deploy_path }}/secrets/{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ groups['child'] }}"

- name: deploy client keystores and truststores for each mm2 instance
  copy:
    src: "../../files/secrets/oda_root/{{ item }}/"
    dest: "{{ oda_deploy_path }}/secrets/{{ item }}/"
    mode: '0644'
  loop: "{{ groups['child'] }}"

- name: copy oda base files
  copy:
    src: "../../files/oda_base/"
    dest: "{{ oda_deploy_path }}/"
    directory_mode: '0755'

- name: generate oda env file
  template:
    src: ../../templates/env.j2
    dest: "{{ oda_deploy_path }}/{{ env_filename }}"
    mode: '0644'

- name: generate docker compose file
  template:
    src: ../../templates/compose_root.yml.j2
    dest: "{{ oda_deploy_path }}/{{ compose_filename }}"
    mode: '0644'

- name: configure mm2 drift control
  import_tasks: configure_mm2.yml